/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JFrame;
/**
 *
 * @author alejandrosanmiguel
 */
public class vistaAcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form vistaAcercaDe
     */
    public vistaAcercaDe() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalVistaAcercaDe = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        txtIcon = new javax.swing.JLabel();

        panelPrincipalVistaAcercaDe.setBackground(new java.awt.Color(255, 255, 255));


        javax.swing.GroupLayout panelPrincipalVistaAcercaDeLayout = new javax.swing.GroupLayout(panelPrincipalVistaAcercaDe);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipalVistaAcercaDe.setBackground(new java.awt.Color(255, 255, 255));

        labelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        labelTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelTitulo.setText("Acerca de...");

        txtNombre1.setText("Luis Alejandro Sanmiguel Galeano              2220221058");

        txtNombre3.setText("Luis Alejandro Sanmiguel Galeano              2220221058");

        txtNombre2.setText("Luis Alejandro Sanmiguel Galeano              2220221058");

        txtIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/iconAcercaDe.jpg"))); // NOI18N

        panelPrincipalVistaAcercaDe.setLayout(panelPrincipalVistaAcercaDeLayout);
        panelPrincipalVistaAcercaDeLayout.setHorizontalGroup(
            panelPrincipalVistaAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVistaAcercaDeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalVistaAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre2)
                    .addComponent(txtNombre3)
                    .addComponent(txtNombre1)
                    .addGroup(panelPrincipalVistaAcercaDeLayout.createSequentialGroup()
                        .addComponent(txtIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelTitulo)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelPrincipalVistaAcercaDeLayout.setVerticalGroup(
            panelPrincipalVistaAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalVistaAcercaDeLayout.createSequentialGroup()
                .addGroup(panelPrincipalVistaAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalVistaAcercaDeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(labelTitulo))
                    .addGroup(panelPrincipalVistaAcercaDeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(txtNombre1)
                .addGap(17, 17, 17)
                .addComponent(txtNombre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre3)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalVistaAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipalVistaAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaAcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAcercaDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel labelTitulo;

    private javax.swing.JPanel panelPrincipalVistaAcercaDe;
    private javax.swing.JLabel txtIcon;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNombre2;
    private javax.swing.JLabel txtNombre3;
    // End of variables declaration//GEN-END:variables
}
